TRAIN_SPLIT: 120
FORECAST_PERIODS: 23
FREQUENCY: "W-Fri"
DATE_COLUMN: "Date"
TARGET_COLUMN: "Weekly_Sales_x"
STORE_COLUMN: "Store"
SEASONALITY_MODE: "multiplicative"
DAILY_SEASONALITY: false
WEEKLY_SEASONALITY: true
YEARLY_SEASONALITY: true