artifacts_root: artifacts

data_injestion:
  root_dir: artifacts/data_injestion
  source_url: "https://drive.google.com/file/d/1o3b5F60AKd245z__9mFBvC_CbsLLoH6S/view?usp=drive_link"
  local_data_file: artifacts/data_injestion/dataset.zip
  unzip_dir: artifacts/data_injestion